![image.png](attachment:image.png)

# Numpy

Numpy is THE library for scientific computing and linear algebra in Python's community and was designed to give users the best of both worlds in programming languages: the speed of `C` language with the readability and elegance of `Python`.

### Why Numpy?
A question arises that why do we need NumPy when python lists are already there. The answer to it is we cannot perform operations on all the elements of two list directly. For example we cannot multiply two lists directly we will have to do it element wise. This is where the role of NumPy comes into play.

In [ ]:
from numpy import *
import numpy as np

Very quick speed comparison to show the staggering difference in performance, don't bother about the code in the following cell.

In [1]:
import numpy as np
import time
import gc # garbage collection
import sys


def compare_times(f1, f2, setup1=None, setup2=None, runs=30):
    print('    format: mean seconds (standard error)', runs, 'runs')
    maxpad = max(len(f.__name__) for f in (f1, f2))
    means = []
    for setup, f in [[setup1, f1], [setup2, f2]]:
        setup = (lambda: tuple()) if setup is None else setup
        
        total_times = []
        for _ in range(runs):
            try:
                gc.disable()
                args = setup()
                
                start = time.time()
                if isinstance(args, tuple):
                    f(*args)
                else:
                    f(args)
                end = time.time()
                
                total_times.append(end - start)
            finally:
                gc.enable()
                
        mean = np.mean(total_times)
        se = np.std(total_times) / np.sqrt(len(total_times))
        print('    {} {:.2e} ({:.2e})'.format(f.__name__.ljust(maxpad), mean, se))
        means.append(mean)
    print('    improvement ratio {:.1f}'.format(means[0] / means[1]))

In [2]:
size = 10 ** 7 
print('create a list 1, 2, ...', size)


def create_list(): return list(range(size))
def create_array(): return np.arange(size, dtype=int)

compare_times(create_list, create_array)

create a list 1, 2, ... 10000000
    format: mean seconds (standard error) 30 runs
    create_list  4.50e-01 (2.42e-02)
    create_array 1.57e-02 (1.26e-04)
    improvement ratio 28.6


In [ ]:
import time
num = 10000000
a = np.random.random(num)
b = np.random.random(num)

star = time.time()
c = np.dot(a,b)
en = time.time()
print(c)
print("Verctorize  : " +  str((en -star)*1000) + 'ms')

d =0
start = time.time()
for i in range(num):
    d += a[i]*b[i]
end = time.time()

print(d)
print("Loop version  : " +  str((end -start)*1000) + 'ms')
print("Vectorization is faster by" , (end -start)/(en -star) , 'times')

2499632.0268662428
Verctorize  : 12.294769287109375ms
2499632.026866403
Loop version  : 4796.185493469238ms
Vectorization is faster by 390.0996742165684 times


### Convinced about numpy powers? ... Now, let's practice!

#### Q1: Create a 1D array of numbers from 0 to 9.


In [4]:
arr1 = np.array([1,2,3])
arr1.ndim

1

#### Q2: Extract all odd numbers from arr.


In [5]:
arr2 = np.array([1,2,3,8,6,4,7,5,2,1] )
np.extract(arr2 %2 !=0 , arr2 )                 # extract ( condition , array )

array([1, 3, 7, 5, 1])

#### Q3: Replace all odd numbers in arr with -1.


In [7]:
arr3 = np.array([1,2,3,8,6,4,7,5,2,1] )
arr3[arr3%2 == 1] = -1 

arr3

array([-1,  2, -1,  8,  6,  4, -1, -1,  2, -1])

#### Q4: Convert a 1D array of length 10 to a 2D array with 2 rows


In [22]:
arr4 = np.array([1,2,3,4,5,6,7,8,9,10] )
arr4.resize(2,5)
print(f' array     = {arr4} ')
print(f' dimontion = {arr4.ndim} D ')

 array     = [[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 
 dimontion = 2 D 


#### Q5: compute the square root for each element in the  array
#### ([[1, 2, 3],[2, 3, 4],[4, 5, 6]])


In [25]:
arr5 = np.array([[1, 2, 3],[2, 3, 4],[4, 5, 6]])
arr5 **=2
arr5

array([[ 1,  4,  9],
       [ 4,  9, 16],
       [16, 25, 36]])

#### Q6: compute the exponential for each element in the above array


In [26]:
np.exp(arr5)

array([[2.71828183e+00, 5.45981500e+01, 8.10308393e+03],
       [5.45981500e+01, 8.10308393e+03, 8.88611052e+06],
       [8.88611052e+06, 7.20048993e+10, 4.31123155e+15]])

#### Q7: sample 8 elements from uniform dist ([0, 1)


In [27]:
arr6 = np.random.uniform(0,1,8)
arr6

array([0.09266303, 0.06594019, 0.38795426, 0.77774884, 0.77422844,
       0.3721994 , 0.23433721, 0.08510075])

#### Q8: Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

#### Q9: Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21

In [28]:
matrx1 = np.random.randint(10,21,(3,4)) 
matrx1

array([[20, 13, 12, 15],
       [13, 15, 17, 18],
       [11, 10, 14, 19]])

#### Q10: Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

In [36]:
vector1 = np.random.randint(5,50,10)
vector1

array([15, 46, 36, 30, 46, 33, 11,  8, 37, 42])

#### Q11: Write a NumPy program to create an array of all the even integers from 30 to 70.

In [41]:
array = np.arange(30,71)
even_arr= np.extract(array%2==0,array)
even_arr

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

#### Q12: Write a NumPy program to check whether two arrays are equal (element wise) or not

In [88]:
def check( x, y ):
  x=np.array(x)
  y=np.array(y)
  z=1
  v=1
  for i in x.shape:
    z*=i
  for i in y.shape:
    v*=i
  if z == v :
    print(' True ')
  else:
    print('False')

check(  [[ 1,2,3 ] , [ 5,6,9 ] , [8,9,6]]        ,         [ 1,2,6,5,4,7,8,9,5 ] )

 True 


* further reading: [visit here](https://www.w3resource.com/python-exercises/numpy/index.php)